{% set name = "radiant-mlhub" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radiant_mlhub-{{ version }}.tar.gz
  sha256: 3a5a8e971132d5b4cd9e412c7f6d87894fc588655ae0e93006646927b1ecb902

build:
  number: 0
  noarch: python
  entry_points:
    - mlhub=radiant_mlhub.cli:mlhub
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - click >=7.1.2,<9.0.0
    - pystac ~=1.1.0
    - python >=3.6
    - requests ~=2.25
    - tqdm ~=4.56
    - typing-extensions

test:
  imports:
    - radiant_mlhub
    - test
  commands:
    - pip check
    - mlhub --version
  requires:
    - pip

about:
  home: https://github.com/radiantearth/radiant-mlhub
  summary: A Python client for Radiant MLHub
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://radiant-mlhub.readthedocs.io
  dev_url: https://github.com/radiantearth/radiant-mlhub

extra:
  recipe-maintainers:
    - duckontheweb
